# Generated by Django 4.1.2 on 2022-10-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order_number',
        ),
    ]
