# Generated by Django 4.1.2 on 2022-10-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_customer_temporder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('olindi', 'Olindi'), ('yetkazildi', 'Yetkazildi')], default='yangi', max_length=100),
        ),
    ]
