# Generated by Django 4.1.2 on 2022-10-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
