# Generated by Django 4.1.2 on 2022-10-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('olindi', 'Olindi'), ('yetkazildi', 'Yetkazildi')], default='yangi', max_length=100)),
                ('qayerdan', models.CharField(max_length=1000)),
                ('qayerga', models.CharField(max_length=1000)),
                ('person_count', models.CharField(default=1, max_length=100)),
                ('price', models.IntegerField(default=100000)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archorder_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archdriver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
